if (BUILD_SHARED_LIBS)
    message("")
    message(" *** WITH_DYNAMIC_LINKING - INFO!")
    message(" *** Will link against shared libraries!")
    message(" *** Please note that this is an experimental feature!")
    add_definitions(-DSERENITY_API_USE_DYNAMIC_LINKING)
endif ()